<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Vps running server error PI</title>
    <link>https://forum.moparisthebest.com/t/vps-running-server-error-pi/447394</link>
    <description>Well when i run my server on my vps i just bought it spams like non-stop mysql errors... I have highscores, webclient, vote4cash, and donating, is that why it&#39;s spamming the errors?

I&#39;ll try and post the errors.

Help appreciated thanks!!

Edit: Heres the error! 
[code][6/29/12 2:31 PM]: [Region] DONE LOADING REGION CONFIGURATIONS
[6/29/12 2:31 PM]: Server ONLINE.
[6/29/12 2:31 PM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,340,976,693,583 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[6/29/12 2:31 PM]:      at server.util.SQL.createConnection(SQL.java:18)
[6/29/12 2:31 PM]:      at server.Server$1.execute(Server.java:165)
[6/29/12 2:31 PM]:      at server.task.Task.tick(Task.java:107)
[6/29/12 2:31 PM]:      at server.task.TaskScheduler.run(TaskScheduler.java:125)

[6/29/12 2:31 PM]:      at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask$Sync.innerRunAndReset
(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask.runAndReset(Unknown S
ource)
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche
duledFutureTask.access$301(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche
duledFutureTask.run(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[6/29/12 2:31 PM]:      at java.lang.Thread.run(Unknown Source)
[6/29/12 2:31 PM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,340,976,693,583 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[6/29/12 2:31 PM]:      ... 23 more
[6/29/12 2:31 PM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[6/29/12 2:31 PM]:      at java.net.TwoStacksPlainSocketImpl.socketConnect(Nativ
e Method)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.doConnect(Unknown So
urce)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Unk
nown Source)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connect(Unknown Sour
ce)
[6/29/12 2:31 PM]:      at java.net.PlainSocketImpl.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.SocksSocketImpl.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[6/29/12 2:31 PM]:      ... 24 more
[6/29/12 2:31 PM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,340,976,694,958 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[6/29/12 2:31 PM]:      at server.util.SQL.createConnection(SQL.java:18)
[6/29/12 2:31 PM]:      at server.Server$1.execute(Server.java:165)
[6/29/12 2:31 PM]:      at server.task.Task.tick(Task.java:107)
[6/29/12 2:31 PM]:      at server.task.TaskScheduler.run(TaskScheduler.java:125)

[6/29/12 2:31 PM]:      at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask$Sync.innerRunAndReset
(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask.runAndReset(Unknown S
ource)
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche
duledFutureTask.access$301(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche
duledFutureTask.run(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[6/29/12 2:31 PM]:      at java.lang.Thread.run(Unknown Source)
[6/29/12 2:31 PM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,340,976,694,958 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[6/29/12 2:31 PM]:      ... 23 more
[6/29/12 2:31 PM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[6/29/12 2:31 PM]:      at java.net.TwoStacksPlainSocketImpl.socketConnect(Nativ
e Method)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.doConnect(Unknown So
urce)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Unk
nown Source)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connect(Unknown Sour
ce)
[6/29/12 2:31 PM]:      at java.net.PlainSocketImpl.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.SocksSocketImpl.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[6/29/12 2:31 PM]:      ... 24 more
[6/29/12 2:31 PM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,340,976,696,426 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[6/29/12 2:31 PM]:      at server.util.SQL.createConnection(SQL.java:18)
[6/29/12 2:31 PM]:      at server.Server$1.execute(Server.java:165)
[6/29/12 2:31 PM]:      at server.task.Task.tick(Task.java:107)
[6/29/12 2:31 PM]:      at server.task.TaskScheduler.run(TaskScheduler.java:125)

[6/29/12 2:31 PM]:      at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask$Sync.innerRunAndReset
(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask.runAndReset(Unknown S
ource)
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche
duledFutureTask.access$301(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche
duledFutureTask.run(Unknown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[6/29/12 2:31 PM]:      at java.lang.Thread.run(Unknown Source)
[6/29/12 2:31 PM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,340,976,696,426 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[6/29/12 2:31 PM]:      ... 23 more
[6/29/12 2:31 PM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[6/29/12 2:31 PM]:      at java.net.TwoStacksPlainSocketImpl.socketConnect(Nativ
e Method)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.doConnect(Unknown So
urce)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Unk
nown Source)
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connect(Unknown Sour
ce)
[6/29/12 2:31 PM]:      at java.net.PlainSocketImpl.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.SocksSocketImpl.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[6/29/12 2:31 PM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[6/29/12 2:31 PM]:      ... 24 more
[/code]

Please help will rep++</description>
    
    <lastBuildDate>Fri, 29 Jun 2012 13:28:36 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/vps-running-server-error-pi/447394.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Vps running server error PI</title>
        <dc:creator><![CDATA[@s_3_3_m_3 s 3 3 m 3]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/s_3_3_m_3">@s_3_3_m_3</a> wrote:</p>
          <blockquote>
              <p>Well when i run my server on my vps i just bought it spams like non-stop mysql errors… I have highscores, webclient, vote4cash, and donating, is that why it’s spamming the errors?</p>
<p>I’ll try and post the errors.</p>
<p>Help appreciated thanks!!</p>
<p>Edit: Heres the error!</p>
<p>[code][6/29/12 2:31 PM]: [Region] DONE LOADING REGION CONFIGURATIONS<br>
[6/29/12 2:31 PM]: Server ONLINE.<br>
[6/29/12 2:31 PM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,340,976,693,583 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[6/29/12 2:31 PM]:      at server.util.SQL.createConnection(SQL.java:18)<br>
[6/29/12 2:31 PM]:      at server.Server$1.execute(Server.java:165)<br>
[6/29/12 2:31 PM]:      at server.task.Task.tick(Task.java:107)<br>
[6/29/12 2:31 PM]:      at server.task.TaskScheduler.run(TaskScheduler.java:125)</p>
<p>[6/29/12 2:31 PM]:      at java.util.concurrent.Executors$RunnableAdapter.call(U<br>
nknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask$Sync.innerRunAndReset<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask.runAndReset(Unknown S<br>
ource)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche<br>
duledFutureTask.access$301(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche<br>
duledFutureTask.run(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk<br>
nown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un<br>
known Source)<br>
[6/29/12 2:31 PM]:      at java.lang.Thread.run(Unknown Source)<br>
[6/29/12 2:31 PM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,340,976,693,583 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[6/29/12 2:31 PM]:      … 23 more<br>
[6/29/12 2:31 PM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[6/29/12 2:31 PM]:      at java.net.TwoStacksPlainSocketImpl.socketConnect(Nativ<br>
e Method)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.doConnect(Unknown So<br>
urce)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Unk<br>
nown Source)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connect(Unknown Sour<br>
ce)<br>
[6/29/12 2:31 PM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.(Unknown Source)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[6/29/12 2:31 PM]:      … 24 more<br>
[6/29/12 2:31 PM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,340,976,694,958 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[6/29/12 2:31 PM]:      at server.util.SQL.createConnection(SQL.java:18)<br>
[6/29/12 2:31 PM]:      at server.Server$1.execute(Server.java:165)<br>
[6/29/12 2:31 PM]:      at server.task.Task.tick(Task.java:107)<br>
[6/29/12 2:31 PM]:      at server.task.TaskScheduler.run(TaskScheduler.java:125)</p>
<p>[6/29/12 2:31 PM]:      at java.util.concurrent.Executors$RunnableAdapter.call(U<br>
nknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask$Sync.innerRunAndReset<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask.runAndReset(Unknown S<br>
ource)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche<br>
duledFutureTask.access$301(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche<br>
duledFutureTask.run(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk<br>
nown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un<br>
known Source)<br>
[6/29/12 2:31 PM]:      at java.lang.Thread.run(Unknown Source)<br>
[6/29/12 2:31 PM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,340,976,694,958 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[6/29/12 2:31 PM]:      … 23 more<br>
[6/29/12 2:31 PM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[6/29/12 2:31 PM]:      at java.net.TwoStacksPlainSocketImpl.socketConnect(Nativ<br>
e Method)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.doConnect(Unknown So<br>
urce)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Unk<br>
nown Source)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connect(Unknown Sour<br>
ce)<br>
[6/29/12 2:31 PM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.(Unknown Source)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[6/29/12 2:31 PM]:      … 24 more<br>
[6/29/12 2:31 PM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,340,976,696,426 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[6/29/12 2:31 PM]:      at server.util.SQL.createConnection(SQL.java:18)<br>
[6/29/12 2:31 PM]:      at server.Server$1.execute(Server.java:165)<br>
[6/29/12 2:31 PM]:      at server.task.Task.tick(Task.java:107)<br>
[6/29/12 2:31 PM]:      at server.task.TaskScheduler.run(TaskScheduler.java:125)</p>
<p>[6/29/12 2:31 PM]:      at java.util.concurrent.Executors$RunnableAdapter.call(U<br>
nknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask$Sync.innerRunAndReset<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.FutureTask.runAndReset(Unknown S<br>
ource)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche<br>
duledFutureTask.access$301(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ScheduledThreadPoolExecutor$Sche<br>
duledFutureTask.run(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk<br>
nown Source)<br>
[6/29/12 2:31 PM]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un<br>
known Source)<br>
[6/29/12 2:31 PM]:      at java.lang.Thread.run(Unknown Source)<br>
[6/29/12 2:31 PM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,340,976,696,426 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[6/29/12 2:31 PM]:      at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[6/29/12 2:31 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[6/29/12 2:31 PM]:      … 23 more<br>
[6/29/12 2:31 PM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[6/29/12 2:31 PM]:      at java.net.TwoStacksPlainSocketImpl.socketConnect(Nativ<br>
e Method)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.doConnect(Unknown So<br>
urce)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Unk<br>
nown Source)<br>
[6/29/12 2:31 PM]:      at java.net.AbstractPlainSocketImpl.connect(Unknown Sour<br>
ce)<br>
[6/29/12 2:31 PM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.connect(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.(Unknown Source)<br>
[6/29/12 2:31 PM]:      at java.net.Socket.(Unknown Source)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[6/29/12 2:31 PM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[6/29/12 2:31 PM]:      … 24 more<br>
[/code]</p>
<p>Please help will rep++</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/vps-running-server-error-pi/447394/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/vps-running-server-error-pi/447394/1</link>
        <pubDate>Fri, 29 Jun 2012 13:28:36 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-447394-1</guid>
        <source url="https://forum.moparisthebest.com/t/vps-running-server-error-pi/447394.rss">Vps running server error PI</source>
      </item>
  </channel>
</rss>
